# =============================================================================
# k8s/monitoring/health-check-deployment.yaml
# Simple Health Check Deployment
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-deployment
  namespace: bookmynurse
  labels:
    app: health-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check
  template:
    metadata:
      labels:
        app: health-check
    spec:
      containers:
      - name: health-check
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: health-config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: health-config
        configMap:
          name: health-check-config