apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  labels:
    app: backup-storage
    component: storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /var/lib/kubernetes/backup
    type: DirectoryOrCreate
