# =============================================================================
# k8s/ingress/ingress.yaml
# Ingress Controller for External Traffic Management
# Configured to run alongside Apache on different ports
# =============================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bmn-ingress
  namespace: bookmynurse
  annotations:
    # Enable SSL redirect (commented out for now)
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Enable CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    # Certificate manager (commented out for now)
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Rate limiting
    nginx.ingress.kubernetes.io/rate-limit-connections: "10"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    # Proxy settings
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
spec:
  ingressClassName: nginx
  # TLS configuration removed for now to avoid validation errors
  rules:
  - http:
      paths:
      # Health check - must come first (Exact match)
      - path: /health
        pathType: Exact
        backend:
          service:
            name: backend-service
            port:
              number: 30008
      # API routes - must come second (Exact match)
      - path: /api/health
        pathType: Exact
        backend:
          service:
            name: backend-service
            port:
              number: 30008
      # Frontend routes - catch-all (must come last)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8080