# =============================================================================
# k8s/frontend/service.yaml
# Frontend Service (ClusterIP for internal access)
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bookmynurse
  labels:
    app: frontend
    tier: web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: frontend
    tier: web