# =============================================================================
# k8s/mysql/init-configmap.yaml
# Database initialization scripts
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: bookmynurse
data:
  # Add your nursingBackend.sql content here
  init-db.sql: |
    /*
    SQLyog Community v13.3.0 (64 bit)
    MySQL - 8.0.41 : Database - nursing_db
    *********************************************************************
    */

    /*!40101 SET NAMES utf8 */;

    /*!40101 SET SQL_MODE='''''';

    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='''''NO_AUTO_VALUE_ON_ZERO'''' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
    CREATE DATABASE /*!32312 IF NOT EXISTS*/`bookmynurse` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION=''''N'''' */;

    USE `bookmynurse`;

    /*Table structure for table `bookings` */

    DROP TABLE IF EXISTS `bookings`;

    CREATE TABLE `bookings` (
      `id` int NOT NULL AUTO_INCREMENT,
      `name` varchar(255) NOT NULL,
      `mobile` varchar(15) NOT NULL,
      `nurseType` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
      `location` varchar(255) NOT NULL,
      `services` varchar(255) NOT NULL,
      `preferences` varchar(50) NOT NULL,
      `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
      `enquiryno` varchar(50) NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    /*Data for the table `bookings` */

    insert  into `bookings`(`id`,`name`,`mobile`,`nurseType`,`location`,`services`,`preferences`,`created_at`,`enquiryno`) values 
    (1,''''Messi'''',''''9856325412'''',''''Male'''',''''Bangalore'''',''''Elder Care'''',''''24hrs'''',''''2025-01-06 17:45:38'''',''''ED-1747585452146''''),
    (4,''''Neymar'''',''''9595965911'''',''''Male'''',''''Spain'''',''''Tracheostomy Patient Care'''',''''12hrs'''',''''2025-01-08 13:11:32'''',''''TP-1758652365896''''),
    (13,''''Pedri'''',''''9857458885'''',''''Male'''',''''Madurai'''',''''Elder Care'''',''''24hrs'''',''''2025-03-19 10:52:46'''',''''ED-1742361766524'''');

    /*Table structure for table `clientusers` */

    DROP TABLE IF EXISTS `clientusers`;

    CREATE TABLE `clientusers` (
      `id` int NOT NULL AUTO_INCREMENT,
      `email` varchar(255) NOT NULL,
      `phone_number` varchar(15) NOT NULL,
      `password` varchar(255) NOT NULL,
      `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`),
      UNIQUE KEY `email` (`email`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    /*Data for the table `clientusers` */

    insert  into `clientusers`(`id`,`email`,`phone_number`,`password`,`created_at`) values 
    (1,''''messi@gmail.com'''',''''9876543212'''',''''$2a$10$uAC220ZXQMmN5kf5DD.7BOD5fPni59.eftso9OYNV3P2qwvX03IsC'''',''''2025-03-18 23:09:16'''');

    /*Table structure for table `images` */

    DROP TABLE IF EXISTS `images`;

    CREATE TABLE `images` (
      `id` int NOT NULL AUTO_INCREMENT,
      `file_path` varchar(255) NOT NULL,
      `uploaded_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    /*Data for the table `images` */

    insert  into `images`(`id`,`file_path`,`uploaded_at`) values 
    (10,''''uploads\1738231760637-60360103.png'''',''''2025-01-30 15:39:20''''),
    (11,''''uploads\1738231921298-479094622.jpeg'''',''''2025-01-30 15:42:01''''),
    (12,''''uploads\1738656037979-548052802.jpg'''',''''2025-02-04 13:30:38''''),
    (13,''''uploads\1738674105875-7875530.jpeg'''',''''2025-02-04 18:31:45''''),
    (14,''''uploads\1738674774770-148508176.jpeg'''',''''2025-02-04 18:42:54''''),
    (15,''''uploads\1738734308367-513574658.jpeg'''',''''2025-02-05 11:15:08''''),
    (16,''''uploads\1739184925861-348638238.png'''',''''2025-02-10 16:25:26''''),
    (17,''''uploads\1739185035405-858299321.png'''',''''2025-02-10 16:27:15''''),
    (18,''''uploads\1739790382468-517659713.jpeg'''',''''2025-02-17 16:36:22''''),
    (19,''''uploads\1739790813365-810962880.jpeg'''',''''2025-02-17 16:43:33''''),
    (20,''''uploads\1739877400050-637262909.jpeg'''',''''2025-02-18 16:46:40''''),
    (21,''''uploads\1739967884464-211754781.jpg'''',''''2025-02-19 17:54:44'''');

    /*Table structure for table `registration` */

    DROP TABLE IF EXISTS `registration`;

    CREATE TABLE `registration` (
      `id` int NOT NULL AUTO_INCREMENT,
      `name` varchar(255) NOT NULL DEFAULT ''''''',
      `aadhaar` varchar(12) NOT NULL,
      `mobile` varchar(10) NOT NULL,
      `email` varchar(255) NOT NULL,
      `gender` enum(''''male'''',''''female'''') NOT NULL,
      `dob` date NOT NULL,
      `education` varchar(255) NOT NULL,
      `experience` int NOT NULL,
      `languages` json DEFAULT NULL,
      `specialization` varchar(255) NOT NULL,
      `address` text NOT NULL,
      `base_location` varchar(255) NOT NULL,
      `image_id` int NOT NULL,
      `approval_status` enum(''''Pending'''',''''Approved'''',''''Rejected'''') DEFAULT ''''Pending'''',
      `serviceopt` json DEFAULT NULL,
      `from_time` varchar(10) NOT NULL,
      `to_time` varchar(10) NOT NULL,
      `availability` enum(''''Available'''',''''Busy'''',''''Pending'''') DEFAULT ''''Pending'''',
      PRIMARY KEY (`id`),
      UNIQUE KEY `aadhaar` (`aadhaar`),
      KEY `image_id` (`image_id`),
      CONSTRAINT `registration_ibfk_1` FOREIGN KEY (`image_id`) REFERENCES `images` (`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    /*Data for the table `registration` */

    insert  into `registration`(`id`,`name`,`aadhaar`,`mobile`,`email`,`gender`,`dob`,`education`,`experience`,`languages`,`specialization`,`address`,`base_location`,`image_id`,`approval_status`,`serviceopt`,`from_time`,`to_time`,`availability`) values 
    (5,''''Messi'''',''''101452563999'''',''''9854785698'''',''''messi@gmail.com'''',''''male'''',''''1987-06-24'''',''''B.Sc.,'''',10,''''["English", "Hindi"]'''',''''Elder Care Specialist'''',''''Argentina'''',''''Barcelona'''',11,''''Pending'''',''''["24 Hours"]'''',''''9:00 AM'''',''''6:00 PM'''',''''Available''''),
    (7,''''Alexia'''',''''985874525632'''',''''9854589658'''',''''messi@gmail.com'''',''''female'''',''''1996-08-14'''',''''B.Sc.,'''',3,''''["Tamil", "English"]'''',''''Elder Care Specialist'''',''''Nungampaakam, Chennai'''',''''Chennai'''',13,''''Approved'''',''''["12 Hours"]'''',''''8:00 AM'''',''''12:30 PM'''',''''Available''''),
    (8,''''Ms Dhoni'''',''''857456525411'''',''''9854525632'''',''''messi.22cs@licet.ac.in'''',''''male'''',''''1981-07-07'''',''''M.Sc.,'''',7,''''["Tamil", "English", "Hindi"]'''',''''Tracheostomy Specialist'''',''''Chennai'''',''''Chennai'''',14,''''Approved'''',''''["8 Hours"]'''',''''10:00 AM'''',''''5:30 PM'''',''''Available''''),
    (9,''''Messi'''',''''985452563254'''',''''9854565854'''',''''messi@gmail.com'''',''''male'''',''''1987-06-24'''',''''A.N.M.,'''',12,''''["Tamil", "Hindi"]'''',''''ICU Setup Specialist'''',''''Chennai'''',''''Chennai'''',15,''''Pending'''',''''["4 Hours"]'''',''''8:30 AM'''',''''5:00 PM'''',''''Pending''''),
    (12,''''Pedri'''',''''956325425555'''',''''7854125633'''',''''service@gmail.com'''',''''male'''',''''1965-04-24'''',''''Diploma Nursing,'''',6,''''["Tamil", "Hindi"]'''',''''ICU Setup Specialist'''',''''Nungambakam'''',''''Chennai'''',19,''''Approved'''',''''["6 Hours"]'''',''''10:30 AM'''',''''7:00 PM'''',''''Busy'''');

    /*Table structure for table `users` */

    DROP TABLE IF EXISTS `users`;

    CREATE TABLE `users` (
      `id` int NOT NULL AUTO_INCREMENT,
      `username` varchar(255) NOT NULL,
      `password` varchar(255) NOT NULL,
      `role` enum(''''user'''',''''admin'''') NOT NULL DEFAULT ''''user'''',
      PRIMARY KEY (`id`),
      UNIQUE KEY `username` (`username`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    /*Data for the table `users` */

    insert  into `users`(`id`,`username`,`password`,`role`) values 
    (1,''''messi'''',''''$2a$10$oiPhWogFeRFg3nAkmJxeHO3d219repa.ahwMlD9OSE6Ixu0ewWitq'''',''''admin'''');

    /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;