# =============================================================================
# k8s/mysql/pvc.yaml
# Persistent Volume Claim for MySQL data
# =============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: bookmynurse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage