version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: localpass
      MYSQL_DATABASE: bookmynurse
      MYSQL_USER: app_user
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /mnt/d/BMN/FULL STACK/nursingBackend.sql:/docker-entrypoint-initdb.d/nursingBackend.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-plocalpass"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ../backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: bookmynurse
      DB_USER: app_user
      DB_PASSWORD: apppass
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
